# Generated by Django 5.0 on 2023-12-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='Image',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
