# Generated by Django 5.0 on 2023-12-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='tour_lead',
        ),
    ]
